Diagnosis tree norsk
Konfidens/freud pull request #29
Opened 2023-08-01 11:47 UTC by joddern

The diagnosis.ts router has two endpoints: "createFileAndEmbedd" which can use the "dsm_norsk_nettside.html" file from https://finnkode.ehelse.no/#icd10/1/0/0/-1, to parse it into categories and diagnoses and then embeds this into a weaviate vector store. Also has functions for writing to json file.

The other endpoint: "queryTheDatabase" is supposed to be used in the chat.tsx file as a "second module" where symptoms can be plotted in and followup questions must be answered to pinpoint a diagnoses suggestion. This is only in norwegian for now (the website above is norwegian).

2023-08-01 11:50 UTC, joddern commented
[dsm_norsk_nettside_textformat.txt](https://github.com/Konfidens/freud/files/12228736/dsm_norsk_nettside_textformat.txt)

2023-08-02 07:09 UTC, fredrikrab requested changes
Very cool! I added the three comments we also talked about in person for reference

2023-08-02 07:09 UTC, fredrikrab commented on src/components/Chat.tsx
> +      <Button onClick={toggleSymptomsMode}> Toggle symptoms-mode </Button>
How can be make the UI for this feature neat?

2023-08-02 07:09 UTC, fredrikrab commented on src/server/api/routers/diagnosis.ts
> +      const NUM_SOURCES = 5;
Move "magic constants" to the very top?

2023-08-02 07:09 UTC, fredrikrab commented on src/server/api/routers/diagnosis.ts
> +        console.debug("\nnewSymptom: ", newSymptom);
Remove debug statements before merging to dev?

2023-08-02 08:01 UTC, davidlekve commented on src/components/Chat.tsx
> +      console.log("QUERYING!");
please remove

2023-08-02 08:02 UTC, joddern commented on src/components/Chat.tsx
> +      <Button onClick={toggleSymptomsMode}> Toggle symptoms-mode </Button>
I don't know

2023-08-02 08:05 UTC, davidlekve commented on src/components/MessageComponent.tsx
> +          {message.sources ? (
Change to &&

2023-08-02 08:30 UTC, fredrikrab approved these changes

2023-08-02 10:53 UTC, merged